### ISSUE TITLE
I'm having trouble managing repositories of a Organisation in Gitea

### ISSUE THREAD

**Issue by pfmephisto** [maikebing/Gitea.VisualStudio#1]
I have an organisation set up in Gitea with its own repositories and my user account as Owner of the organisation. When I log in to my account through Visual Studio I can manage my own repositories, but I don't see the ones belonging to the organisation. Am I doing something wrong with my set up or is this a feature that is not being supported by Gitea for Visual Studio?

**Comment by maikebing** [comment]
This feature is not supported. This vs extension user looks less and has not tried to do more. When I'm not busy, I'll find a way to support it.

**Comment by maikebing** [comment]
Several inhancements, including Added option to create or publish to organizations. #2
