### ISSUE TITLE
Upgrade git packages 

### ISSUE THREAD

**Issue by jsil3601** [maikebing/Gitea.VisualStudio#12]
**Is your feature request related to a problem? Please describe.**
Currently gitea4vs uses a relatively older version of the git nugget packages. 
This does not support newer features added to git, such as using the windows certificate store instead of the openssl one. 

**Describe the solution you'd like**
Upgrade the nugget packages to latest. 
I did this on local build and it compiles fine. 

**Describe alternatives you've considered**

Installing the CA cert on the extension open ssl store. But that does not seem strait forward at all. 

**Additional context**

**Comment by maikebing** [comment]
Hi , try this . 
http://vsixgallery.com/extension/62991164-1F3E-4AAA-BF2F-537C83AF987C/

**Comment by jsil3601** [comment]
Hi maikebing,

Thanks for the quick response
with new package we get passed the authentication, but still getting an error when cloning;
The login works fine.
then when click on clone, we see the list of repos, select the one, and click clone.
at that point we get 
"Git failed with a fatal error.
unable to access 'https://zzz.yyy.com:3000/MyOrg/myrepo.git/': SSL certificate problem: self signed certificate in certificate chain"

we can clone the repository from git gui - The certificate CA is in the windows store so the certificate is  trusted.
at the time of installing git, one of setup steps is to choose if to use openssl as the source of certificates or windows certificate store.
we choose windows certificate store.
maybe there is/ create a way to tell gitea4vs to use windows certificate store?

below screenshot of setup step in git installation:
![gitsetup](https://user-images.githubusercontent.com/32902287/57627857-7edb5a80-75a1-11e9-851b-0e302f7e05b3.jpg)

**Comment by jsil3601** [comment]
Update:

The issue with self signed cert and the windows cert store actually has nothing to do with the extension.
its a hidden 'feature' of microsoft;

for anyone having the same issue, you can change visual studio git implementation to use windows cert store : (VS is shipped with its own git and not using the default git on the PC).
1. browse to 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\Git\mingw32\bin
2. run
git config --global http.sslBackend schannel

Thanks again @maikebing for the fast response
