### ISSUE TITLE
Unable to sign in when gitea url has postfix

### ISSUE THREAD

**Issue by glacios** [maikebing/Gitea.VisualStudio#13]
**Describe the bug**
Unable to sign in to account when gitea located in subfolder (e.g. http://server.org/gitea/).

**To Reproduce**
1. Host gitea in subfolder (`http://server.org/gitea/`)
2. In gitea vs extension enter url (`http://server.org/gitea/`), login and password of existing gitea user
3. Click on 'Login'
4. See error 'Login failed'

**Expected behavior**
Successfully logged in

**Desktop (please complete the following information):**
 - OS: [e.g. windows 7]
 - VS 2019 16.1.3

**Additional context information:**
Located cause of such behavior: https://github.com/maikebing/Gitea.VisualStudio/blob/e6992e0164bf569814d2aa5e2f8bf7b32f64d7f3/src/Gitea.VisualStudio/Services/WebService.cs#L81-L86
After host (`http://server.org/gitea/`) had been parsed to `Uri`, it's used only `Host` (`server.org`) to create client used for log in

In api client created by composing host and port from arguments so log-in operation performed with url `http://server.org/` and ended up being failure
https://github.com/maikebing/gitea.net/blob/0010f56c0cdb82656bae26523e7afc3429aba43d/Gitea.API/v1/Client.cs#L198-L200

**Comment by maikebing** [comment]
Can you give me a test account and address?

**Comment by bushadam** [comment]
i get seam bug,the gitea server with nginx 
url is https://server/gitea/
login error

**Comment by maikebing** [comment]
@MokhamedDakhraui @bushadam   Try new version 
https://ci.appveyor.com/project/MaiKeBing/gitea-visualstudio/build/artifacts

**Comment by bushadam** [comment]
@maikebing  thx,the new version work fine for me.
