### ISSUE TITLE
Cannot search this from Visual Studio Code Extentions,I hope the author can publish this to the vscode as soon as possible

### ISSUE THREAD

**Issue by wzyxdwll** [maikebing/Gitea.VisualStudio#15]
![image](https://user-images.githubusercontent.com/24530906/68920656-e40e4380-07b0-11ea-99a1-ea27d9ab9519.png)

**Comment by maikebing** [comment]
VSCode is completely different from VS's technology stack and is not what I'm good at, so hopefully someone else can do it.
