### ISSUE TITLE
Update from version 0.0.0.1 not possible

### ISSUE THREAD

**Issue by confusedsushi** [maikebing/Gitea.VisualStudio#5]
I try to update from version 0.0.0.1

![gitea-extension-1](https://user-images.githubusercontent.com/6968196/53481544-beec7000-3a7d-11e9-92e9-9d6839dd17fa.png)

That gives this error after closing Visual Studio 2017

![gitea-extension-2](https://user-images.githubusercontent.com/6968196/53481545-beec7000-3a7d-11e9-83ac-7b8883beabca.png)

**Comment by maikebing** [comment]
@confusedsushi  
Because canceling the installation to all users makes it easy to update automatically, you need to uninstall the old version and reinstall it once.

@troygeiger

**Comment by confusedsushi** [comment]
That worked. Thanks for clarifying, I expected something like this.
