### ISSUE TITLE
PublishSectionViewModel

### ISSUE THREAD

**Issue by maikebing** [maikebing/Gitea.VisualStudio#7]
**Describe the bug**
System.NullReferenceException: 未将对象引用设置到对象的实例。
   在 Gitea.TeamFoundation.ViewModels.PublishSectionViewModel.LoadResources()
   在 Gitea.TeamFoundation.ViewModels.PublishSectionViewModel..ctor(IMessenger messenger, IGitService git, IShellService shell, IStorage storage, ITeamExplorerServices tes, IViewFactory viewFactory, IWebService web)
   在 Gitea.TeamFoundation.Sync.GiteaPublishSection.InitializeView(SectionInitializeEventArgs e)
   在 Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerSectionBase.Initialize(Object sender, SectionInitializeEventArgs e)
   在 Gitea.TeamFoundation.Sync.GiteaPublishSection.Initialize(Object sender, SectionInitializeEventArgs e)
   在 Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

**Comment by troygeiger** [comment]
My guess would be that the credential was not found at the Target when calling _storage.GetUser().
